image: docker:git
services:
  - docker:dind

stages:
  - build
  - deploy

variables:
  MAVEN_OPTS: "-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"

cache:
  paths:
    - /root/.m2/repository/

mvnpackage:
  image: maven:3-jdk-8
  stage: build
  script:
    - 'mvn $MAVEN_CLI_OPTS -f common/pom.xml install'
    - 'mvn $MAVEN_CLI_OPTS -f notifier/pom.xml package'
  artifacts:
    paths:
      - notifier/target/surefire-reports/*
      - notifier/target/notifierservice.fat.jar

release:
  stage: deploy
  services:
    - docker:dind
  script:
    - docker build -f notifier/Dockerfile -t notifierservice .