language: java
sudo: required
dist: trusty
services:
  - docker

before_install:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

script:
  - mvn deploy -Dmaven.javadoc.skip=true
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

addons:
  sonarcloud:
    organization: sijmenhuizenga-github
    token:
      secure: $SONARCLOUD
    branches:
      - develop

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'