version: "3"
services:
  notifier:
    image: sijmenhuizenga/movienotifier:notifier-service
    ports:
      - 81:80
    environment:
      NOTIFIER_FB_MESSENGER_TOKEN:
      NOTIFIER_MAILGUN_SECRET:
      NOTIFIER_MAILGUN_DOMAIN:
      NOTIFIER_MAILGUN_FROMNAME:
      NOTIFIER_MAILGUN_FROMEMAIL:
      NOTIFIER_AWSSNS_ACCESSKEY:
      NOTIFIER_AWSSNS_SECRETKEY: